
path_classifiers:
  generated:
    - exclude: "src/*" 
  library:
    - exclude: "src/*"
  template:
    - exclude: "src/*"
  test: 
    - exclude: "test/*"
    - test            
  docs:
    - README.md
    - LICENSE.txt
extraction:
  cpp:
    index:
        build_command:
        - ./cmake.py --common && ./cmake.py