language: cpp

jobs:
  include:
    - os: linux
      dist: focal
    - os: linux
      dist: bionic
    - os: linux
      dist: xenial
    - os: osx
      osx_image: xcode7.2

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt install -y python3; fi
  
script:
  - python3 cmake.py --common
  - python3 cmake.py