language: cpp

jobs:
  include:
    - os: linux
      dist: focal
      arch: amd64
    - os: linux
      dist: bionic
      arch: amd64
    - os: linux
      dist: xenial
      arch: amd64
#    - os: windows
      
before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt install -y python3; fi
  
script:
  - python cmake.py --external
  - python cmake.py
  - python test.py